# Generated by Django 5.2.8 on 2025-11-28 13:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_pageview_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pageview',
            name='store_pv_session_key_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='store_pv_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='store_pv_path_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='duration',
            field=models.FloatField(blank=True, help_text='Time on page in seconds', null=True),
        ),
    ]
