# Generated by Django 5.2.7 on 2025-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='contact_email',
            field=models.EmailField(default='no-email@example.com', help_text='Email address for correspondence.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_name',
            field=models.CharField(default='Anonymous Customer', help_text='Name of the person requesting the service.', max_length=200),
            preserve_default=False,
        ),
    ]
