# Generated by Django 5.2.7 on 2025-10-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_attachments/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicerequest')),
            ],
        ),
    ]
