# Generated by Django 5.2.7 on 2025-10-19 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicerequest_attachment_serviceattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('QUOTED', 'Quote Sent'), ('ACCEPTED', 'Quote Accepted'), ('COMPLETE', 'Job Completed'), ('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=20),
        ),
    ]
