# Generated by Django 5.2.8 on 2025-11-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_quotemessage_user_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Phone number for contact.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address for correspondence.', max_length=254, null=True),
        ),
    ]
